"use client"

import { TreeComponent } from "@/components/tree-component"

const catalogData = {
  catalog: [
    {
      id: "cat_1",
      name: "Electronics",
      level: "category",
      products: [
        {
          id: "prod_1",
          name: "Universal Remote Control",
          price: 29.99,
          stock: 150,
        },
        {
          id: "prod_2",
          name: "HDMI Cable 6ft",
          price: 12.99,
          stock: 300,
        },
        {
          id: "prod_3",
          name: "USB-C Hub 7-in-1",
          price: 45.99,
          stock: 80,
        },
        {
          id: "prod_4",
          name: "Wireless Charging Pad",
          price: 24.99,
          stock: 200,
        },
        {
          id: "prod_5",
          name: "Power Bank 20000mAh",
          price: 39.99,
          stock: 120,
        },
        {
          id: "prod_6",
          name: "Screen Protector Kit",
          price: 14.99,
          stock: 250,
        },
        {
          id: "prod_7",
          name: "Cable Management Box",
          price: 18.99,
          stock: 90,
        },
        {
          id: "prod_8",
          name: "Surge Protector 12 Outlet",
          price: 34.99,
          stock: 100,
        },
        {
          id: "prod_9",
          name: "Anti-Static Wrist Strap",
          price: 8.99,
          stock: 180,
        },
        {
          id: "prod_10",
          name: "Digital Multimeter",
          price: 28.99,
          stock: 60,
        },
      ],
      subcategories: [
        {
          id: "subcat_1_1",
          name: "Computers & Laptops",
          level: "subcategory",
          products: [
            {
              id: "prod_11",
              name: "Laptop Cooling Pad",
              price: 32.99,
              stock: 75,
            },
            {
              id: "prod_12",
              name: "Keyboard Cover Protector",
              price: 9.99,
              stock: 200,
            },
            {
              id: "prod_13",
              name: "Laptop Stand Adjustable",
              price: 44.99,
              stock: 95,
            },
            {
              id: "prod_14",
              name: "USB Keyboard & Mouse Combo",
              price: 28.99,
              stock: 140,
            },
            {
              id: "prod_15",
              name: "Webcam Cover Slider",
              price: 5.99,
              stock: 300,
            },
            {
              id: "prod_16",
              name: "Laptop Sleeve 15 inch",
              price: 19.99,
              stock: 110,
            },
            {
              id: "prod_17",
              name: "External DVD Writer",
              price: 34.99,
              stock: 50,
            },
            {
              id: "prod_18",
              name: "Monitor Privacy Filter",
              price: 42.99,
              stock: 65,
            },
            {
              id: "prod_19",
              name: "Docking Station USB-C",
              price: 129.99,
              stock: 45,
            },
            {
              id: "prod_20",
              name: "Laptop Battery External",
              price: 79.99,
              stock: 30,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_1_1_1",
              name: "Gaming Laptops",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_21",
                  name: "RGB Gaming Laptop 17 inch",
                  price: 1499.99,
                  stock: 25,
                },
                {
                  id: "prod_22",
                  name: "Gaming Laptop RTX 4060",
                  price: 1299.99,
                  stock: 30,
                },
                {
                  id: "prod_23",
                  name: "High Performance Gaming Laptop",
                  price: 1899.99,
                  stock: 15,
                },
                {
                  id: "prod_24",
                  name: "Budget Gaming Laptop GTX",
                  price: 899.99,
                  stock: 40,
                },
                {
                  id: "prod_25",
                  name: "Ultra Thin Gaming Laptop",
                  price: 1699.99,
                  stock: 20,
                },
                {
                  id: "prod_26",
                  name: "Gaming Laptop 32GB RAM",
                  price: 2199.99,
                  stock: 12,
                },
                {
                  id: "prod_27",
                  name: "RGB Mechanical Gaming Keyboard",
                  price: 89.99,
                  stock: 80,
                },
                {
                  id: "prod_28",
                  name: "Gaming Mouse 16000 DPI",
                  price: 59.99,
                  stock: 100,
                },
                {
                  id: "prod_29",
                  name: "Gaming Headset 7.1 Surround",
                  price: 79.99,
                  stock: 90,
                },
                {
                  id: "prod_30",
                  name: "Gaming Laptop Backpack",
                  price: 64.99,
                  stock: 55,
                },
              ],
            },
            {
              id: "subsubcat_1_1_2",
              name: "Business Laptops",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_31",
                  name: "Professional Business Laptop 14 inch",
                  price: 1099.99,
                  stock: 45,
                },
                {
                  id: "prod_32",
                  name: "Ultrabook i7 16GB",
                  price: 1399.99,
                  stock: 35,
                },
                {
                  id: "prod_33",
                  name: "Convertible 2-in-1 Laptop",
                  price: 999.99,
                  stock: 50,
                },
                {
                  id: "prod_34",
                  name: "Business Laptop with Fingerprint",
                  price: 1249.99,
                  stock: 40,
                },
                {
                  id: "prod_35",
                  name: "Lightweight Travel Laptop",
                  price: 899.99,
                  stock: 60,
                },
                {
                  id: "prod_36",
                  name: "Enterprise Security Laptop",
                  price: 1599.99,
                  stock: 28,
                },
                {
                  id: "prod_37",
                  name: "Business Laptop Docking Kit",
                  price: 189.99,
                  stock: 35,
                },
                {
                  id: "prod_38",
                  name: "Professional Laptop Case",
                  price: 49.99,
                  stock: 75,
                },
                {
                  id: "prod_39",
                  name: "Wireless Presenter Remote",
                  price: 29.99,
                  stock: 85,
                },
                {
                  id: "prod_40",
                  name: "Portable Monitor 15.6 inch",
                  price: 179.99,
                  stock: 42,
                },
              ],
            },
          ],
        },
        {
          id: "subcat_1_2",
          name: "Smartphones & Tablets",
          level: "subcategory",
          products: [
            {
              id: "prod_41",
              name: "Phone Case Universal",
              price: 14.99,
              stock: 250,
            },
            {
              id: "prod_42",
              name: "Tempered Glass Screen Protector",
              price: 9.99,
              stock: 300,
            },
            {
              id: "prod_43",
              name: "Car Phone Mount",
              price: 19.99,
              stock: 150,
            },
            {
              id: "prod_44",
              name: "Portable Phone Charger",
              price: 24.99,
              stock: 180,
            },
            {
              id: "prod_45",
              name: "Bluetooth Earbuds",
              price: 49.99,
              stock: 200,
            },
            {
              id: "prod_46",
              name: "Phone Ring Holder",
              price: 7.99,
              stock: 220,
            },
            {
              id: "prod_47",
              name: "Tablet Stand Adjustable",
              price: 22.99,
              stock: 95,
            },
            {
              id: "prod_48",
              name: "Stylus Pen for Tablets",
              price: 29.99,
              stock: 120,
            },
            {
              id: "prod_49",
              name: "Wireless Charging Car Mount",
              price: 39.99,
              stock: 85,
            },
            {
              id: "prod_50",
              name: "MicroSD Card 128GB",
              price: 19.99,
              stock: 280,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_1_2_1",
              name: "Android Phones",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_51",
                  name: "Flagship Android Phone 256GB",
                  price: 899.99,
                  stock: 60,
                },
                {
                  id: "prod_52",
                  name: "Mid-Range Android 128GB",
                  price: 449.99,
                  stock: 85,
                },
                {
                  id: "prod_53",
                  name: "Budget Android Smartphone",
                  price: 199.99,
                  stock: 120,
                },
                {
                  id: "prod_54",
                  name: "5G Android Phone Premium",
                  price: 799.99,
                  stock: 55,
                },
                {
                  id: "prod_55",
                  name: "Android Phone with Stylus",
                  price: 1099.99,
                  stock: 35,
                },
                {
                  id: "prod_56",
                  name: "Foldable Android Phone",
                  price: 1499.99,
                  stock: 20,
                },
                {
                  id: "prod_57",
                  name: "Rugged Android Phone",
                  price: 399.99,
                  stock: 45,
                },
                {
                  id: "prod_58",
                  name: "Camera-Focused Android",
                  price: 699.99,
                  stock: 50,
                },
                {
                  id: "prod_59",
                  name: "Gaming Android Phone",
                  price: 849.99,
                  stock: 40,
                },
                {
                  id: "prod_60",
                  name: "Android Phone Dual SIM",
                  price: 349.99,
                  stock: 95,
                },
              ],
            },
            {
              id: "subsubcat_1_2_2",
              name: "iOS Devices",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_61",
                  name: "iPhone Pro Max 512GB",
                  price: 1399.99,
                  stock: 40,
                },
                {
                  id: "prod_62",
                  name: "iPhone Standard 256GB",
                  price: 999.99,
                  stock: 70,
                },
                {
                  id: "prod_63",
                  name: "iPhone Mini 128GB",
                  price: 699.99,
                  stock: 55,
                },
                {
                  id: "prod_64",
                  name: "iPad Pro 12.9 inch",
                  price: 1099.99,
                  stock: 35,
                },
                {
                  id: "prod_65",
                  name: "iPad Air 256GB",
                  price: 749.99,
                  stock: 60,
                },
                {
                  id: "prod_66",
                  name: "iPad Mini Latest Gen",
                  price: 499.99,
                  stock: 75,
                },
                {
                  id: "prod_67",
                  name: "MagSafe Charger",
                  price: 39.99,
                  stock: 150,
                },
                {
                  id: "prod_68",
                  name: "AirPods Pro",
                  price: 249.99,
                  stock: 100,
                },
                {
                  id: "prod_69",
                  name: "Apple Pencil 2nd Gen",
                  price: 129.99,
                  stock: 85,
                },
                {
                  id: "prod_70",
                  name: "Leather iPhone Case",
                  price: 59.99,
                  stock: 120,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "cat_2",
      name: "Home & Kitchen",
      level: "category",
      products: [
        {
          id: "prod_71",
          name: "Dish Soap Refill Pack",
          price: 12.99,
          stock: 200,
        },
        {
          id: "prod_72",
          name: "All-Purpose Cleaner Spray",
          price: 8.99,
          stock: 250,
        },
        {
          id: "prod_73",
          name: "Microfiber Cleaning Cloths 12-Pack",
          price: 14.99,
          stock: 180,
        },
        {
          id: "prod_74",
          name: "Trash Bags 13 Gallon",
          price: 18.99,
          stock: 300,
        },
        {
          id: "prod_75",
          name: "Paper Towels 12 Rolls",
          price: 24.99,
          stock: 220,
        },
        {
          id: "prod_76",
          name: "Sponges Multi-Pack",
          price: 9.99,
          stock: 280,
        },
        {
          id: "prod_77",
          name: "Rubber Gloves 3 Pairs",
          price: 11.99,
          stock: 150,
        },
        {
          id: "prod_78",
          name: "Broom and Dustpan Set",
          price: 22.99,
          stock: 90,
        },
        {
          id: "prod_79",
          name: "Storage Bins Set of 6",
          price: 34.99,
          stock: 110,
        },
        {
          id: "prod_80",
          name: "Door Mat Non-Slip",
          price: 19.99,
          stock: 130,
        },
      ],
      subcategories: [
        {
          id: "subcat_2_1",
          name: "Kitchen Appliances",
          level: "subcategory",
          products: [
            {
              id: "prod_81",
              name: "Can Opener Electric",
              price: 24.99,
              stock: 85,
            },
            {
              id: "prod_82",
              name: "Kitchen Timer Digital",
              price: 12.99,
              stock: 120,
            },
            {
              id: "prod_83",
              name: "Food Scale Digital",
              price: 19.99,
              stock: 95,
            },
            {
              id: "prod_84",
              name: "Measuring Cups and Spoons Set",
              price: 14.99,
              stock: 150,
            },
            {
              id: "prod_85",
              name: "Knife Sharpener Electric",
              price: 34.99,
              stock: 70,
            },
            {
              id: "prod_86",
              name: "Cutting Board Set 3-Piece",
              price: 22.99,
              stock: 110,
            },
            {
              id: "prod_87",
              name: "Oven Mitts and Pot Holders",
              price: 16.99,
              stock: 140,
            },
            {
              id: "prod_88",
              name: "Utensil Holder Ceramic",
              price: 18.99,
              stock: 100,
            },
            {
              id: "prod_89",
              name: "Spice Rack Organizer",
              price: 29.99,
              stock: 80,
            },
            {
              id: "prod_90",
              name: "Dish Drying Rack",
              price: 26.99,
              stock: 95,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_2_1_1",
              name: "Coffee Makers",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_91",
                  name: "Drip Coffee Maker 12-Cup",
                  price: 49.99,
                  stock: 65,
                },
                {
                  id: "prod_92",
                  name: "Single Serve Coffee Maker",
                  price: 79.99,
                  stock: 80,
                },
                {
                  id: "prod_93",
                  name: "Espresso Machine Automatic",
                  price: 299.99,
                  stock: 30,
                },
                {
                  id: "prod_94",
                  name: "French Press 34oz",
                  price: 29.99,
                  stock: 100,
                },
                {
                  id: "prod_95",
                  name: "Cold Brew Coffee Maker",
                  price: 34.99,
                  stock: 75,
                },
                {
                  id: "prod_96",
                  name: "Pour Over Coffee Set",
                  price: 24.99,
                  stock: 90,
                },
                {
                  id: "prod_97",
                  name: "Coffee Grinder Burr",
                  price: 44.99,
                  stock: 55,
                },
                {
                  id: "prod_98",
                  name: "Milk Frother Electric",
                  price: 19.99,
                  stock: 110,
                },
                {
                  id: "prod_99",
                  name: "Coffee Filters 200-Count",
                  price: 7.99,
                  stock: 200,
                },
                {
                  id: "prod_100",
                  name: "Thermal Coffee Carafe",
                  price: 32.99,
                  stock: 70,
                },
              ],
            },
            {
              id: "subsubcat_2_1_2",
              name: "Blenders & Mixers",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_101",
                  name: "High-Power Blender 1500W",
                  price: 129.99,
                  stock: 45,
                },
                {
                  id: "prod_102",
                  name: "Personal Blender 2-Pack",
                  price: 39.99,
                  stock: 90,
                },
                {
                  id: "prod_103",
                  name: "Immersion Hand Blender",
                  price: 34.99,
                  stock: 80,
                },
                {
                  id: "prod_104",
                  name: "Stand Mixer 6-Quart",
                  price: 199.99,
                  stock: 35,
                },
                {
                  id: "prod_105",
                  name: "Hand Mixer 5-Speed",
                  price: 29.99,
                  stock: 100,
                },
                {
                  id: "prod_106",
                  name: "Smoothie Blender with Cups",
                  price: 44.99,
                  stock: 70,
                },
                {
                  id: "prod_107",
                  name: "Food Processor 12-Cup",
                  price: 89.99,
                  stock: 50,
                },
                {
                  id: "prod_108",
                  name: "Bullet Blender System",
                  price: 59.99,
                  stock: 85,
                },
                {
                  id: "prod_109",
                  name: "Countertop Blender Glass Jar",
                  price: 54.99,
                  stock: 60,
                },
                {
                  id: "prod_110",
                  name: "Blender Bottles 4-Pack",
                  price: 24.99,
                  stock: 120,
                },
              ],
            },
          ],
        },
        {
          id: "subcat_2_2",
          name: "Furniture",
          level: "subcategory",
          products: [
            {
              id: "prod_111",
              name: "Furniture Polish Spray",
              price: 9.99,
              stock: 150,
            },
            {
              id: "prod_112",
              name: "Furniture Pads 100-Pack",
              price: 12.99,
              stock: 200,
            },
            {
              id: "prod_113",
              name: "Wood Touch-Up Markers",
              price: 14.99,
              stock: 85,
            },
            {
              id: "prod_114",
              name: "Furniture Sliders Set",
              price: 11.99,
              stock: 110,
            },
            {
              id: "prod_115",
              name: "Cable Clips 50-Pack",
              price: 8.99,
              stock: 180,
            },
            {
              id: "prod_116",
              name: "Under-Desk Cable Tray",
              price: 19.99,
              stock: 70,
            },
            {
              id: "prod_117",
              name: "Furniture Anchors Safety Kit",
              price: 16.99,
              stock: 95,
            },
            {
              id: "prod_118",
              name: "LED Strip Lights 16ft",
              price: 24.99,
              stock: 130,
            },
            {
              id: "prod_119",
              name: "Drawer Organizer Set",
              price: 22.99,
              stock: 100,
            },
            {
              id: "prod_120",
              name: "Shelf Liner Non-Adhesive",
              price: 13.99,
              stock: 140,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_2_2_1",
              name: "Living Room Furniture",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_121",
                  name: "3-Seater Sofa Gray",
                  price: 599.99,
                  stock: 25,
                },
                {
                  id: "prod_122",
                  name: "Loveseat Recliner",
                  price: 499.99,
                  stock: 30,
                },
                {
                  id: "prod_123",
                  name: "Accent Chair Modern",
                  price: 199.99,
                  stock: 50,
                },
                {
                  id: "prod_124",
                  name: "Coffee Table Wood",
                  price: 149.99,
                  stock: 40,
                },
                {
                  id: "prod_125",
                  name: "TV Stand 65 inch",
                  price: 179.99,
                  stock: 35,
                },
                {
                  id: "prod_126",
                  name: "End Tables Set of 2",
                  price: 89.99,
                  stock: 55,
                },
                {
                  id: "prod_127",
                  name: "Bookshelf 5-Tier",
                  price: 79.99,
                  stock: 60,
                },
                {
                  id: "prod_128",
                  name: "Ottoman Storage Cube",
                  price: 59.99,
                  stock: 70,
                },
                {
                  id: "prod_129",
                  name: "Floor Lamp Tripod",
                  price: 69.99,
                  stock: 45,
                },
                {
                  id: "prod_130",
                  name: "Area Rug 8x10",
                  price: 199.99,
                  stock: 30,
                },
              ],
            },
            {
              id: "subsubcat_2_2_2",
              name: "Bedroom Furniture",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_131",
                  name: "Queen Bed Frame Metal",
                  price: 249.99,
                  stock: 35,
                },
                {
                  id: "prod_132",
                  name: "King Platform Bed",
                  price: 399.99,
                  stock: 20,
                },
                {
                  id: "prod_133",
                  name: "Nightstand 2-Drawer",
                  price: 89.99,
                  stock: 60,
                },
                {
                  id: "prod_134",
                  name: "6-Drawer Dresser White",
                  price: 299.99,
                  stock: 25,
                },
                {
                  id: "prod_135",
                  name: "Wardrobe Closet Portable",
                  price: 149.99,
                  stock: 40,
                },
                {
                  id: "prod_136",
                  name: "Vanity Table with Mirror",
                  price: 199.99,
                  stock: 30,
                },
                {
                  id: "prod_137",
                  name: "Bed Headboard Upholstered",
                  price: 129.99,
                  stock: 45,
                },
                {
                  id: "prod_138",
                  name: "Under-Bed Storage Boxes",
                  price: 34.99,
                  stock: 80,
                },
                {
                  id: "prod_139",
                  name: "Bedside Table Lamp Set",
                  price: 44.99,
                  stock: 70,
                },
                {
                  id: "prod_140",
                  name: "Full-Length Mirror Standing",
                  price: 79.99,
                  stock: 50,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "cat_3",
      name: "Sports & Outdoors",
      level: "category",
      products: [
        {
          id: "prod_141",
          name: "Water Bottle 32oz",
          price: 14.99,
          stock: 250,
        },
        {
          id: "prod_142",
          name: "Gym Towel Microfiber",
          price: 9.99,
          stock: 200,
        },
        {
          id: "prod_143",
          name: "Resistance Bands Set",
          price: 19.99,
          stock: 150,
        },
        {
          id: "prod_144",
          name: "Jump Rope Adjustable",
          price: 12.99,
          stock: 180,
        },
        {
          id: "prod_145",
          name: "Yoga Mat 6mm",
          price: 24.99,
          stock: 140,
        },
        {
          id: "prod_146",
          name: "Sports Duffel Bag",
          price: 34.99,
          stock: 100,
        },
        {
          id: "prod_147",
          name: "Fitness Tracker Watch",
          price: 49.99,
          stock: 120,
        },
        {
          id: "prod_148",
          name: "Workout Gloves",
          price: 16.99,
          stock: 160,
        },
        {
          id: "prod_149",
          name: "Foam Roller",
          price: 22.99,
          stock: 90,
        },
        {
          id: "prod_150",
          name: "Compression Socks 3-Pack",
          price: 18.99,
          stock: 170,
        },
      ],
      subcategories: [
        {
          id: "subcat_3_1",
          name: "Fitness Equipment",
          level: "subcategory",
          products: [
            {
              id: "prod_151",
              name: "Dumbbells Set 5-50 lbs",
              price: 299.99,
              stock: 40,
            },
            {
              id: "prod_152",
              name: "Kettlebell 20 lbs",
              price: 34.99,
              stock: 80,
            },
            {
              id: "prod_153",
              name: "Exercise Ball 65cm",
              price: 19.99,
              stock: 100,
            },
            {
              id: "prod_154",
              name: "Pull-Up Bar Doorway",
              price: 29.99,
              stock: 70,
            },
            {
              id: "prod_155",
              name: "Ab Roller Wheel",
              price: 14.99,
              stock: 120,
            },
            {
              id: "prod_156",
              name: "Medicine Ball 10 lbs",
              price: 24.99,
              stock: 85,
            },
            {
              id: "prod_157",
              name: "Ankle Weights 5 lbs Pair",
              price: 19.99,
              stock: 95,
            },
            {
              id: "prod_158",
              name: "Balance Board Trainer",
              price: 39.99,
              stock: 60,
            },
            {
              id: "prod_159",
              name: "Push-Up Bars",
              price: 16.99,
              stock: 110,
            },
            {
              id: "prod_160",
              name: "Weight Bench Adjustable",
              price: 149.99,
              stock: 35,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_3_1_1",
              name: "Cardio Equipment",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_161",
                  name: "Treadmill Folding Electric",
                  price: 599.99,
                  stock: 20,
                },
                {
                  id: "prod_162",
                  name: "Exercise Bike Stationary",
                  price: 299.99,
                  stock: 30,
                },
                {
                  id: "prod_163",
                  name: "Elliptical Machine",
                  price: 499.99,
                  stock: 18,
                },
                {
                  id: "prod_164",
                  name: "Rowing Machine Magnetic",
                  price: 399.99,
                  stock: 22,
                },
                {
                  id: "prod_165",
                  name: "Stair Stepper Machine",
                  price: 179.99,
                  stock: 35,
                },
                {
                  id: "prod_166",
                  name: "Mini Exercise Bike",
                  price: 79.99,
                  stock: 50,
                },
                {
                  id: "prod_167",
                  name: "Under Desk Treadmill",
                  price: 349.99,
                  stock: 25,
                },
                {
                  id: "prod_168",
                  name: "Spin Bike Indoor",
                  price: 449.99,
                  stock: 20,
                },
                {
                  id: "prod_169",
                  name: "Air Bike Assault Style",
                  price: 599.99,
                  stock: 15,
                },
                {
                  id: "prod_170",
                  name: "Jump Rope Smart Counter",
                  price: 24.99,
                  stock: 90,
                },
              ],
            },
            {
              id: "subsubcat_3_1_2",
              name: "Strength Training",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_171",
                  name: "Barbell Set 300 lbs",
                  price: 399.99,
                  stock: 25,
                },
                {
                  id: "prod_172",
                  name: "Power Rack Squat Cage",
                  price: 599.99,
                  stock: 15,
                },
                {
                  id: "prod_173",
                  name: "Olympic Weight Plates Set",
                  price: 299.99,
                  stock: 30,
                },
                {
                  id: "prod_174",
                  name: "Adjustable Dumbbells 52 lbs",
                  price: 349.99,
                  stock: 20,
                },
                {
                  id: "prod_175",
                  name: "Cable Machine Home Gym",
                  price: 799.99,
                  stock: 12,
                },
                {
                  id: "prod_176",
                  name: "Smith Machine",
                  price: 899.99,
                  stock: 10,
                },
                {
                  id: "prod_177",
                  name: "Hex Dumbbells 5-50 lbs Set",
                  price: 449.99,
                  stock: 18,
                },
                {
                  id: "prod_178",
                  name: "Weight Lifting Gloves Pro",
                  price: 24.99,
                  stock: 80,
                },
                {
                  id: "prod_179",
                  name: "Lifting Straps Pair",
                  price: 14.99,
                  stock: 100,
                },
                {
                  id: "prod_180",
                  name: "Weightlifting Belt Leather",
                  price: 49.99,
                  stock: 55,
                },
              ],
            },
          ],
        },
        {
          id: "subcat_3_2",
          name: "Outdoor Recreation",
          level: "subcategory",
          products: [
            {
              id: "prod_181",
              name: "Camping Flashlight LED",
              price: 19.99,
              stock: 150,
            },
            {
              id: "prod_182",
              name: "Insulated Water Bottle",
              price: 24.99,
              stock: 180,
            },
            {
              id: "prod_183",
              name: "Portable Camping Chair",
              price: 29.99,
              stock: 110,
            },
            {
              id: "prod_184",
              name: "Hiking Backpack 40L",
              price: 59.99,
              stock: 70,
            },
            {
              id: "prod_185",
              name: "Waterproof Dry Bag",
              price: 16.99,
              stock: 130,
            },
            {
              id: "prod_186",
              name: "Pocket Multi-Tool",
              price: 22.99,
              stock: 160,
            },
            {
              id: "prod_187",
              name: "Emergency Blanket 4-Pack",
              price: 12.99,
              stock: 200,
            },
            {
              id: "prod_188",
              name: "Trekking Poles Pair",
              price: 34.99,
              stock: 85,
            },
            {
              id: "prod_189",
              name: "Portable Hammock",
              price: 29.99,
              stock: 95,
            },
            {
              id: "prod_190",
              name: "Camping Cookware Set",
              price: 44.99,
              stock: 75,
            },
          ],
          sub_subcategories: [
            {
              id: "subsubcat_3_2_1",
              name: "Camping Gear",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_191",
                  name: "4-Person Tent Waterproof",
                  price: 149.99,
                  stock: 40,
                },
                {
                  id: "prod_192",
                  name: "Sleeping Bag 20°F",
                  price: 69.99,
                  stock: 60,
                },
                {
                  id: "prod_193",
                  name: "Camping Cot Portable",
                  price: 79.99,
                  stock: 45,
                },
                {
                  id: "prod_194",
                  name: "Camping Lantern Rechargeable",
                  price: 29.99,
                  stock: 90,
                },
                {
                  id: "prod_195",
                  name: "Portable Camp Stove",
                  price: 34.99,
                  stock: 70,
                },
                {
                  id: "prod_196",
                  name: "Camping Table Folding",
                  price: 49.99,
                  stock: 55,
                },
                {
                  id: "prod_197",
                  name: "Camping Pillow Inflatable",
                  price: 14.99,
                  stock: 100,
                },
                {
                  id: "prod_198",
                  name: "Sleeping Pad Self-Inflating",
                  price: 44.99,
                  stock: 65,
                },
                {
                  id: "prod_199",
                  name: "Camp Chairs Set of 2",
                  price: 54.99,
                  stock: 50,
                },
                {
                  id: "prod_200",
                  name: "Portable Fire Pit",
                  price: 89.99,
                  stock: 35,
                },
              ],
            },
            {
              id: "subsubcat_3_2_2",
              name: "Hiking Equipment",
              level: "sub-subcategory",
              products: [
                {
                  id: "prod_201",
                  name: "Hiking Boots Waterproof Men",
                  price: 89.99,
                  stock: 60,
                },
                {
                  id: "prod_202",
                  name: "Hiking Boots Women",
                  price: 89.99,
                  stock: 55,
                },
                {
                  id: "prod_203",
                  name: "Hydration Pack 2L",
                  price: 39.99,
                  stock: 75,
                },
                {
                  id: "prod_204",
                  name: "GPS Navigation Device",
                  price: 199.99,
                  stock: 30,
                },
                {
                  id: "prod_205",
                  name: "Hiking Backpack 65L",
                  price: 129.99,
                  stock: 40,
                },
                {
                  id: "prod_206",
                  name: "Trail Running Shoes",
                  price: 79.99,
                  stock: 70,
                },
                {
                  id: "prod_207",
                  name: "Compass with Mirror",
                  price: 19.99,
                  stock: 90,
                },
                {
                  id: "prod_208",
                  name: "Hiking First Aid Kit",
                  price: 29.99,
                  stock: 85,
                },
                {
                  id: "prod_209",
                  name: "Gaiters for Hiking",
                  price: 24.99,
                  stock: 65,
                },
                {
                  id: "prod_210",
                  name: "Portable Water Filter",
                  price: 34.99,
                  stock: 80,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-950 dark:to-slate-900 p-4">
      <div className="max-w-2xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">Product Catalog</h1>
          <p className="text-slate-600 dark:text-slate-400">Browse categories, subcategories, and products</p>
        </div>
        <TreeComponent data={catalogData.catalog} />
      </div>
    </main>
  )
}
